services:
  app:
    build:
      context: .
      args:
        NB_UID: 200
    image: octopus-aiida

    volumes:
      - type: bind
        source: ${POSTOPUS_SOURCE}
        target: /workspace/postopus
      - type: bind
        source: ./
        target: /workspace/aiida-plugin

    working_dir: /workspace/aiida-plugin
    command: bash
