[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "aiida-octopus"
version = "0.1.0"
description = "AiiDA plugin for running and parsing Octopus calculations"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
    { name = "Alexander Buccheri", email = "alexander.buccheri@mpsd.mpg.de" },
]
keywords = ["AiiDA", "Octopus", "electronic structure", "materials science"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: AiiDA",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "aiida-core>=2.0,<3",
    "postopus>=0.5.0,<0.6",
]

[project.optional-dependencies]
release = [
    "build>=1,<2",
    "twine>=5,<7",
]
tests = [
    "pgtest>=1.3",
    "pytest>=8,<9",
]

# Filter warnings resulting from using a depreciated version of AiiDA
[tool.pytest.ini_options]
filterwarnings = [
    "ignore:Creating AiiDA configuration folder `.*`:UserWarning",
    "ignore:The `Code` class is deprecated\\..*:aiida.common.warnings.AiidaDeprecationWarning",
    "ignore:Object of type <DbNode> not in session, add operation along 'DbUser\\.dbnodes' will not proceed:sqlalchemy.exc.SAWarning",
    "ignore:Object of type <DbNode> not in session, add operation along 'DbComputer\\.dbnodes' will not proceed:sqlalchemy.exc.SAWarning",
]

[project.entry-points."aiida.calculations"]
"octopus.ground_state" = "aiida_octopus.calculations.ground_state:OctopusGSCalculation"

[project.entry-points."aiida.parsers"]
"octopus.ground_state" = "aiida_octopus.parsers.ground_state:OctopusGSParser"

[tool.flit.module]
name = "aiida_octopus"

[tool.flit.sdist]
include = [
    "src/",
    "tests/",
    "README.md",
    "LICENSE",
]
exclude = [
    ".env",
    ".idea/",
    ".pytest_cache/",
    "compose.yml",
    "Dockerfile",
    "**/__pycache__/",
]
